run:
  timeout: 5m
  tests: false
  silent: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable:
    - wsl
    - gochecknoglobals
    - lll
    - funlen
    - gochecknoinits
    - sqlclosecheck
    - dupl
    - gci
    - nlreturn
    - bodyclose

issues:
  exclude-use-default: false
  exclude:
    - G102
    - G304
    - G204
