name: Dependabot
on:
  push:
    branches:
      - 'dependabot/**'
jobs:
  go-vendor:
    runs-on: ubuntu-latest
    container: 'golang:1.14'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Fix detached HEAD
        run: git checkout ${GITHUB_REF#refs/heads/}
      - name: Vendor dependencies
        run: make modules
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.AUDIOHUB_GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit --amend --no-edit
            git push --force-with-lease
          fi
